name: Merge gh-pages to main

on:
  schedule:
    - cron: '0 3 * * *'  # 每天早上3点（UTC时间）运行
  workflow_dispatch: # 允许手动触发这个工作流

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Merge gh-pages into main
      run: |
        git checkout main
        git merge gh-pages --allow-unrelated-histories -m "Merge gh-pages into main"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
